# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWrE6ZceCmtvPnuxMl4n9_ZnDoBGDyp7
"""

1. Business Objective
Tujuan bisnis dari penggunaan Daily Food and Nutrition Dataset adalah untuk memahami pola makan harian dan kandungan gizi dalam makanan yang dikonsumsi oleh individu.
Berdasarkan data tersebut, bisnis dapat mengembangkan aplikasi atau solusi berbasis data yang bertujuan untuk:
Menyediakan rekomendasi diet yang lebih personal dan sesuai dengan tujuan kesehatan penggunanya (misalnya, penurunan berat badan, peningkatan energi, atau pemeliharaan kesehatan jantung).
Membantu perusahaan makanan untuk merancang produk baru yang lebih sehat dan lebih sesuai dengan kebutuhan gizi konsumen.
Mengembangkan aplikasi kesehatan atau kebugaran yang dapat membantu pengguna memantau konsumsi gizi harian mereka dan mencapainya dengan lebih baik.
Memberikan wawasan kepada ahli gizi dan institusi kesehatan untuk melakukan penyuluhan tentang pola makan sehat dan mengurangi penyakit yang terkait dengan diet yang buruk (misalnya obesitas, diabetes).

Assess Situation
Dataset ini terdiri dari informasi tentang makanan dan gizi yang dikonsumsi setiap hari. Memahami struktur dataset dan kualitas data (apakah ada missing value, outliers, atau kesalahan lainnya) sangat penting untuk analisis lebih lanjut.
Keterbatasan Data: Pastikan dataset sudah cukup lengkap dan mencakup berbagai jenis makanan yang umum dikonsumsi, serta mencatat dengan jelas komposisi gizi setiap makanan.

Data Mining Goals
Untuk menggali wawasan bermanfaat dari dataset yang ada, seperti mengidentifikasi pola makan dan mengelompokkan makanan berdasarkan kandungan
gizinya misalnya, makanan kaya protein, rendah kalori, tinggi serat. Selain itu, proyek ini bertujuan untuk mengembangkan sistem rekomendasi diet menggunakan teknik machine learning, serta menganalisis hubungan antara pola makan dan kesehatan,
seperti kaitannya dengan obesitas atau penyakit jantung. Proyek ini juga berfokus pada analisis korelasi antara makanan dan nilai gizi yang diperoleh,
serta menyusun pola makan optimal yang memenuhi standar gizi yang direkomendasikan.

Project Plan

1. Fase Persiapan Data:

Langkah: Mengumpulkan, membersihkan, dan mempersiapkan data yang relevan untuk analisis lebih lanjut. Ini termasuk mengatasi data yang hilang, menghapus duplikasi, dan memastikan konsistensi format.
Tujuan: Memastikan data yang digunakan berkualitas tinggi dan bebas dari kesalahan, serta siap untuk analisis lebih lanjut.

2. Fase Eksplorasi Data:
Langkah: Menggunakan teknik eksplorasi data untuk menganalisis distribusi kalori, kandungan gizi, dan hubungan antar variabel dalam dataset.
Tujuan: Mendapatkan wawasan awal mengenai pola makan dan mengidentifikasi faktor yang dapat mempengaruhi kesehatan (misalnya, terlalu banyak lemak atau kurangnya serat dalam makanan).

3. Fase Pengembangan Model:
Langkah: Mengembangkan model untuk klasifikasi makanan berdasarkan kandungan gizi (misalnya, makanan tinggi protein, rendah kalori, dll.), serta algoritma untuk merekomendasikan pola makan yang sehat.
Tujuan: Membuat model yang dapat membantu pengguna memilih makanan sehat berdasarkan analisis konsumsi gizi mereka.

4. Fase Pembuatan Rekomendasi Diet:
Langkah: Menggunakan hasil dari fase pengembangan model untuk membangun sistem rekomendasi diet yang dipersonalisasi berdasarkan data nutrisi yang telah dianalisis.
Tujuan: Memberikan saran diet yang sesuai dengan kebutuhan nutrisi pengguna, termasuk pengaturan kalori, protein, dan asupan gizi lainnya.

5. Fase Evaluasi Model:
Langkah: Menguji akurasi dan efektivitas model menggunakan data uji. Mengevaluasi model dengan metrik seperti akurasi, presisi, dan recall untuk memastikan sistem rekomendasi berfungsi dengan baik.
Tujuan: Memastikan bahwa sistem yang dikembangkan dapat memberikan rekomendasi yang akurat dan bermanfaat bagi pengguna.

6. Fase Implementasi dan Pengujian:
Langkah: Mengimplementasikan sistem rekomendasi dalam aplikasi nyata atau platform web, serta melakukan pengujian dengan pengguna untuk mengumpulkan feedback.
Tujuan: Menyediakan solusi yang berguna bagi pengguna untuk memonitor dan memperbaiki pola makan mereka berdasarkan rekomendasi yang diberikan oleh sistem.

7. Fase Pemeliharaan dan Perbaikan:
Langkah: Melakukan pemeliharaan rutin terhadap sistem dan memperbarui model dengan data terbaru untuk memastikan relevansi dan keakuratannya.
Tujuan: Memastikan sistem tetap efektif dan akurat, serta terus memberikan rekomendasi yang berguna bagi pengguna.

Melalui tahapan-tahapan ini, Bertujuan serta mempromosikan gaya hidup sehat melalui pendekatan yang berbasis data.